Add sam optimized ViT and MLP-Mixer checkpoints
google-research/vision_transformer pull request #119
Opened 2021-07-02 20:55 UTC by xiangning-chen

2021-07-02 21:01 UTC, xiangning-chen commented
@googlebot I signed it!

2021-07-07 17:36 UTC, andsteing requested changes
Thanks for adding these! Looks good, added some nits mostly about formatting...

2021-07-07 17:36 UTC, andsteing commented on README.md
> +**Update (2.7.2021)**: Added the "When Vision Transformers Outperform ResNets..." paper, and SAM optimized ViT and MLP-Mixer checkpoints.
Could you break lines at 80 characters?
(We only have lines with links & tables running over the character limit)

2021-07-07 17:36 UTC, andsteing commented on README.md
> +**Update (2.7.2021)**: We added the ViT models trained with [SAM](https://arxiv.org/abs/2010.01412) optimizer on imageNet2012 (with basic Inception-style preprocessing). The resultant ViTs outperform
Maybe introduce the "SAM" abbreviation further up (or here)?

2021-07-07 17:36 UTC, andsteing commented on README.md
> +@misc{chen2021vision,
Maybe `chen2021sam` or `chen2021outperform`?
(Not sure what's customary, but I find it useful to have the most salient word in the reference)

2021-07-07 17:36 UTC, andsteing commented on README.md
> +[`gs://mixer_models/sam`]: https://console.cloud.google.com/storage/mixer_models/sam/
Is this needed multiple times?
Usually we put it after the first paragraph using the reference.

2021-07-07 17:36 UTC, andsteing commented on README.md
> +**Update (2.7.2021)**: We added the ViT models trained with [SAM](https://arxiv.org/abs/2010.01412) optimizer on imageNet2012 (with basic Inception-style preprocessing). The resultant ViTs outperform
Nit: We say "ImageNet" in the main text (maybe you could also fix line 187 👍 )

2021-07-07 17:36 UTC, andsteing commented on README.md
> +**Update (2.7.2021)**: We added the ViT models trained with [SAM](https://arxiv.org/abs/2010.01412) optimizer on imageNet2012 (with basic Inception-style preprocessing). The resultant ViTs outperform
Nit: We say "pre-train" (unfortunately not matching your title...)

2021-07-07 17:36 UTC, andsteing commented on README.md
> +**Update (2.7.2021)**: We added the MLP-Mixer models trained with [SAM](https://arxiv.org/abs/2010.01412) on imageNet2012 without strong augmentations ([`gs://mixer_models/sam`]). The loss landscapes
"active"? "activated"?

2021-07-08 05:43 UTC, andsteing approved these changes

2021-07-08 05:43 UTC, merged